VoltShop/VoltShop/Controllers/AlmacenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VoltShop.Controllers
{
    public class AlmacenController : Controller
    {
        // GET: Almacen
        public ActionResult Index()
        {
            return View();
        }
    }
}

VoltShop/VoltShop/Controllers/EnviosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VoltShop.Controllers
{
    public class EnviosController : Controller
    {
        // GET: Envios
        public ActionResult Index()
        {
            return View();
        }
    }
}

VoltShop/VoltShop/Controllers/OrdenController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VoltShop.Models;

namespace VoltShop.Controllers
{
    [Authorize]
    public class OrdenController : Controller
    {
        private contextoVoltshop db = new contextoVoltshop();

        // GET: Orden
        public ActionResult Index()
        {
            var orden_cliente = db.orden_cliente.Where(o => o.fecha_envio == null).OrderBy(o => o.fecha_creacion).Include(o => o.cliente).Include(o => o.paqueteria);
            return View(orden_cliente.ToList());
        }

        // GET: Orden
        public ActionResult Index1()
        {
            var orden_cliente = db.orden_cliente.Where(o => o.fecha_entrega == null && o.fecha_envio != null).OrderBy(o => o.fecha_creacion).Include(o => o.cliente).Include(o => o.paqueteria);
            return View(orden_cliente.ToList());
        }

        // GET: Orden/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            orden_cliente orden_cliente = db.orden_cliente.Find(id);
            if (orden_cliente == null)
            {
                return HttpNotFound();
            }
            return View(orden_cliente);
        }

        // GET: Orden/Create
        public ActionResult Create()
        {
            ViewBag.id_cliente = new SelectList(db.cliente, "Id", "nombre");
            ViewBag.id_dir_entrega = new SelectList(db.direcciones_entrega, "Id", "calle");
            ViewBag.id_paqueteria = new SelectList(db.paqueteria, "Id", "Nombre");
            return View();
        }

        // POST: Orden/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,fecha_creacion,num_confirmacion,total,id_cliente,id_dir_entrega,id_paqueteria,num_guia,fecha_envio,fecha_entrega")] orden_cliente orden_cliente)
        {
            if (ModelState.IsValid)
            {
                db.orden_cliente.Add(orden_cliente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_cliente = new SelectList(db.cliente, "Id", "nombre", orden_cliente.id_cliente);
            ViewBag.id_dir_entrega = new SelectList(db.direcciones_entrega, "Id", "calle", orden_cliente.id_dir_entrega);
            ViewBag.id_paqueteria = new SelectList(db.paqueteria, "Id", "Nombre", orden_cliente.id_paqueteria);
            return View(orden_cliente);
        }

        // GET: Orden/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            orden_cliente orden_cliente = db.orden_cliente.Find(id);
            if (orden_cliente == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_cliente = new SelectList(db.cliente, "Id", "nombre", orden_cliente.id_cliente);
            ViewBag.id_dir_entrega = new SelectList(db.direcciones_entrega, "Id", "calle", orden_cliente.id_dir_entrega);
            ViewBag.id_paqueteria = new SelectList(db.paqueteria, "Id", "Nombre", orden_cliente.id_paqueteria);
            return View(orden_cliente);
        }

        // GET: Orden/Edit/5
        [HttpGet]
        public ActionResult Edit1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            orden_cliente orden_cliente = db.orden_cliente.Find(id);
            if (orden_cliente == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_cliente = new SelectList(db.cliente, "Id", "nombre", orden_cliente.id_cliente);
            ViewBag.id_dir_entrega = new SelectList(db.direcciones_entrega, "Id", "calle", orden_cliente.id_dir_entrega);
            ViewBag.id_paqueteria = new SelectList(db.paqueteria, "Id", "Nombre", orden_cliente.id_paqueteria);
            return View(orden_cliente);
        }

        // POST: Orden/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,id_paqueteria,num_guia,fecha_envio")] orden_cliente orden_cliente)
        {
            if (ModelState.IsValid)
            {
                orden_cliente o = db.orden_cliente.Find(orden_cliente.Id);
                o.id_paqueteria = orden_cliente.id_paqueteria;
                o.num_guia = orden_cliente.num_guia;
                o.fecha_envio = orden_cliente.fecha_envio;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_cliente = new SelectList(db.cliente, "Id", "nombre", orden_cliente.id_cliente);
            ViewBag.id_dir_entrega = new SelectList(db.direcciones_entrega, "Id", "calle", orden_cliente.id_dir_entrega);
            ViewBag.id_paqueteria = new SelectList(db.paqueteria, "Id", "Nombre", orden_cliente.id_paqueteria);
            return View(orden_cliente);
        }

        // POST: Orden/Edit1/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit1([Bind(Include = "Id,id_paqueteria,fecha_entrega")] orden_cliente orden_cliente)
        {
            if (ModelState.IsValid)
            {
                orden_cliente o = db.orden_cliente.Find(orden_cliente.Id);
                o.fecha_entrega = orden_cliente.fecha_entrega;
                db.SaveChanges();
                return RedirectToAction("Index1");
            }
            ViewBag.id_cliente = new SelectList(db.cliente, "Id", "nombre", orden_cliente.id_cliente);
            ViewBag.id_dir_entrega = new SelectList(db.direcciones_entrega, "Id", "calle", orden_cliente.id_dir_entrega);
            ViewBag.id_paqueteria = new SelectList(db.paqueteria, "Id", "Nombre", orden_cliente.id_paqueteria);
            return View(orden_cliente);
        }

        // GET: Orden/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            orden_cliente orden_cliente = db.orden_cliente.Find(id);
            if (orden_cliente == null)
            {
                return HttpNotFound();
            }
            return View(orden_cliente);
        }

        // POST: Orden/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            orden_cliente orden_cliente = db.orden_cliente.Find(id);
            db.orden_cliente.Remove(orden_cliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VoltShop/VoltShop/Controllers/RHController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VoltShop.Controllers
{
    public class RHController : Controller
    {
        // GET: RH
        public ActionResult Index()
        {
            return View();
        }
    }
}

VoltShop/VoltShop/Views/Shared/_LayoutAlmacen.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/bootstrap.css" />
    <link href="~/Content/Site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet">
    <link href="~/Scripts/bootstrap.js" />
    <link href="~/Scripts/bootstrap.min.js" />
    <link href="~/Scripts/jquery-3.3.1.js" />
    <link href="~/Scripts/jquery-3.3.1.min.js" />
</head>
<body style="background-color:lightgoldenrodyellow">
    <header>
        <div class="container">
            <div class="row" style="justify-content:center;">
                <div class="col-xs-6">
                    <img src="~/Content/Images/logoVoltShop.png" height="70" />
                </div>

                <div class="col-xs-6" id="texto-portada" style="text-align:right;">
                    <h4 style="text-align:center;">La tienda de electricidad más grande de México</h4>
                    <p style="text-align:center;"><i class="fa fa-bolt"></i>¡Vísitanos!<i class="fa fa-bolt"></i></p>
                </div>
            </div>
        </div>
    </header>

    <div class="navbar navbar-inverse" style="font-size:20px; font-weight:bold">
        <div class="container glyphicon-align-center">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Compras", "Index", "Almacen")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Categorias <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Registrar", "Create", "Categorias", null, new { id = "add" })</li>
                            <li>@Html.ActionLink("Actualizar", "Index", "Categorias", null, new { id = "edit" })</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Productos <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Registrar", "Create", "Productos", null, new { id = "add" })</li>
                            <li>@Html.ActionLink("Actualizar", "Index", "Productos", null, new { id = "edit" })</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial1")
            </div>
        </div>
    </div>

    <div class="cuerpo">
        @RenderBody()
    </div>

    <div class="pie">
        <br />
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <img src="~/Content/Images/logoVoltShop.png" height="70" /><br /><br />
                    <p>&copy; @DateTime.Now.Year - Volt </p>

                </div>
                <div class="col-md-2">
                    <p>
                    </p>
                </div>
                <div class="col-md-2">
                    <p>
                    </p>
                </div>

                <div class="col-md-4">
                    <h4>Síguenos en nuestras redes sociales</h4>

                    <a href="#" class="fa fa-facebook" style="font-size: 35px;"></a>


                    <a href="#" class="fa fa-twitter" style="font-size: 35px;"></a>


                    <a href="#" class="fa fa-instagram" style="font-size:35px;"></a>


                    <a href="#" class="fa fa-youtube" style="font-size: 35px;"></a>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

VoltShop/VoltShop/Views/Shared/_LayoutEmpleados.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/bootstrap.css" />
    <link href="~/Content/Site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet">
    <link href="~/Scripts/bootstrap.js" />
    <link href="~/Scripts/bootstrap.min.js" />
    <link href="~/Scripts/jquery-3.3.1.js" />
    <link href="~/Scripts/jquery-3.3.1.min.js" />
</head>
<body style="background-color:lightgoldenrodyellow">
    <header>
        <div class="container">
            <div class="row" style="justify-content:center;">
                <div class="col-xs-6">
                    <img src="~/Content/Images/logoVoltShop.png" height="70" />
                </div>

                <div class="col-xs-6" id="texto-portada" style="text-align:right;">
                    <h4 style="text-align:center;">La tienda de electricidad más grande de México</h4>
                    <p style="text-align:center;"><i class="fa fa-bolt"></i>¡Vísitanos!<i class="fa fa-bolt"></i></p>
                </div>
            </div>
        </div>
    </header>

    <div class="navbar navbar-inverse" style="font-size:20px; font-weight:bold">
        <div class="container glyphicon-align-center">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Empleados", "Index", "RH")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Mis acciones <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Registrar", "Create", "Empleado", null, new { id = "add" })</li>
                            <li>@Html.ActionLink("Actualizar", "Index", "Empleado", null, new { id = "edit" })</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial1")
            </div>
        </div>
    </div>

    <div class="cuerpo">
        @RenderBody()
    </div>

    <div class="pie">
        <br />
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <img src="~/Content/Images/logoVoltShop.png" height="70" /><br /><br />
                    <p>&copy; @DateTime.Now.Year - Volt </p>

                </div>
                <div class="col-md-2">
                    <p>
                    </p>
                </div>
                <div class="col-md-2">
                    <p>
                    </p>
                </div>

                <div class="col-md-4">
                    <h4>Síguenos en nuestras redes sociales</h4>

                    <a href="#" class="fa fa-facebook" style="font-size: 35px;"></a>


                    <a href="#" class="fa fa-twitter" style="font-size: 35px;"></a>


                    <a href="#" class="fa fa-instagram" style="font-size:35px;"></a>


                    <a href="#" class="fa fa-youtube" style="font-size: 35px;"></a>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

VoltShop/VoltShop/Views/Shared/_LayoutEnvios.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <link href="~/Content/bootstrap.css" />
    <link href="~/Content/Site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet">
    <link href="~/Scripts/bootstrap.js" />
    <link href="~/Scripts/bootstrap.min.js" />
    <link href="~/Scripts/jquery-3.3.1.js" />
    <link href="~/Scripts/jquery-3.3.1.min.js" />
</head>
<body style="background-color:lightgoldenrodyellow">
    <header>
        <div class="container">
            <div class="row" style="justify-content:center;">
                <div class="col-xs-6">
                    <img src="~/Content/Images/logoVoltShop.png" height="70" />
                </div>

                <div class="col-xs-6" id="texto-portada" style="text-align:right;">
                    <h4 style="text-align:center;">La tienda de electricidad más grande de México</h4>
                    <p style="text-align:center;"><i class="fa fa-bolt"></i>¡Vísitanos!<i class="fa fa-bolt"></i></p>
                </div>
            </div>
        </div>
    </header>

    <div class="navbar navbar-inverse" style="font-size:20px; font-weight:bold">
        <div class="container glyphicon-align-center">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Almacén", "Index", "Envios", new { area ="" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Paqueterías <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Agregar", "Create", "Paqueterias", null, new { id = "add" })</li>
                            <li>@Html.ActionLink("Actualizar", "Index", "Paqueterias", null, new { id = "list" })</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Ordenes pendientes <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Fecha de envío", "Index", "Orden", null, new { id = "add" })</li>
                            <li>@Html.ActionLink("Fecha de entrga", "Index1", "Orden", null, new { id = "list" })</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial1")
            </div>
        </div>
    </div>

    <div class="cuerpo">
        @RenderBody()
    </div>

    <div class="pie">
        <br />
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <img src="~/Content/Images/logoVoltShop.png" height="70" /><br /><br />
                    <p>&copy; @DateTime.Now.Year - Volt </p>

                </div>
                <div class="col-md-2">
                    <p>
                    </p>
                </div>
                <div class="col-md-2">
                    <p>
                    </p>
                </div>

                <div class="col-md-4">
                    <h4>Síguenos en nuestras redes sociales</h4>

                    <a href="#" class="fa fa-facebook" style="font-size: 35px;"></a>


                    <a href="#" class="fa fa-twitter" style="font-size: 35px;"></a>


                    <a href="#" class="fa fa-instagram" style="font-size:35px;"></a>


                    <a href="#" class="fa fa-youtube" style="font-size: 35px;"></a>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

VoltShop/VoltShop/Views/Shared/_LoginPartial1.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
    @Html.AntiForgeryToken()
        string name = "";
        try
        {
            name = Session["name"].ToString();
        }
        catch(Exception ex)
        {

        }


    <ul class="nav navbar-nav navbar-right">
        <li>
            @Html.ActionLink("Hola " + name + " ", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
        </li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Cerrar sesión</a></li>
    </ul>
    }
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Registrarse", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        <li>@Html.ActionLink("Iniciar sesión", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
    </ul>
}